<a href="https://colab.research.google.com/github/sayonaramagalhaes/Semana-17---Reprograma/blob/main/Df_Trasnplantes_Realizados_RNipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Relatório de Transplantes Realizados (Rio Grande do Norte) - Evolução 2001 - 2023 - Table 1.csv')

In [ ]:
df.head(22)

,Ano,Coração,Fígado,Figado vivo,Figado falecido,Pancreas,Pulmão,Pulmão vivo,Pulmão falecido,Rim,...,Pancreas rim,Intestino Isolado,Multivisceral,Total Orgãos,Córnea,Médula óssea,MO Autólogo,Mo Aparentado,Mo Nap,Total Geral
1,2013,0,3,0,3,0,0,0,0,60,...,0,0,0,63,181,50,21,20,9,294
2,2014,2,2,0,2,0,0,0,0,66,...,0,0,0,70,141,60,31,17,12,271
3,2015,0,0,0,0,0,0,0,0,67,...,0,0,0,67,131,39,20,10,9,237
4,2016,0,0,0,0,0,0,0,0,67,...,0,0,0,67,104,57,24,17,16,228
5,2017,0,0,0,0,0,0,0,0,60,...,0,0,0,60,177,1,1,0,0,238
6,2018,0,0,0,0,0,0,0,0,45,...,0,0,0,45,166,59,42,9,8,270
7,2019,0,0,0,0,0,0,0,0,76,...,0,0,0,76,140,71,49,14,8,287
8,2020,0,0,0,0,0,0,0,0,48,...,0,0,0,48,92,91,63,21,7,231
9,2021,0,0,0,0,0,0,0,0,18,...,0,0,0,18,97,71,40,23,8,186
10,2022,2,0,0,0,0,0,0,0,48,...,0,0,0,50,135,52,27,15,10,237
11,2023,4,0,0,0,0,0,0,0,53,...,0,0,0,57,159,87,62,18,7,303

In [ ]:
#renomear colunas
df.rename(columns={'Unnamed: 0':'Ano'},inplace=True)
df.rename(columns={'Unnamed: 1':'Coração'},inplace=True)
#remover colunas
df.drop(columns=['Unnamed: 2'],inplace=True)
#remomer linha
#df.drop(index=0,inplace=True)

In [ ]:
df.rename(columns={'Unnamed: 3':'Fígado'},inplace=True)
df.rename(columns={'Unnamed: 4':'Figado vivo'},inplace=True)
df.rename(columns={'Unnamed: 5':'Figado falecido'},inplace=True)
df.rename(columns={'Unnamed: 6':'Pancreas'},inplace=True)
df.rename(columns={'Unnamed: 7':'Pulmão'},inplace=True)

In [ ]:
from os import rename
df.rename(columns={'Unnamed: 8':'Pulmão vivo'},inplace=True)
df.rename(columns={'Unnamed: 9':'Pulmão falecido'},inplace=True)
df.rename(columns={'Unnamed: 10':'Rim'},inplace=True)
df.rename(columns={'Unnamed: 11':'Rim vivo'},inplace=True)
df.rename(columns={'Unnamed: 12':'Rim falecido'},inplace=True)
df.rename(columns={'Unnamed: 13':'Pancreas rim'},inplace=True)
df.rename(columns={'Unnamed: 14':'Intestino Isolado'},inplace =True)
df.rename(columns={'Unnamed: 15':'Multivisceral'},inplace =True)
df.rename(columns={'Unnamed: 16':'Total Orgãos'},inplace =True)
df.rename(columns={'Unnamed: 17':'Córnea'},inplace =True)
df.rename(columns={'Unnamed: 18':'Médula óssea'},inplace =True)
df.rename(columns={'Unnamed: 19':'MO Autólogo'},inplace =True)
df.rename(columns={'Unnamed: 20':'Mo Aparentado'},inplace =True)
df.rename(columns={'Unnamed: 21':'Mo Nap'},inplace =True)
df.rename(columns={'Unnamed: 22':'Total Geral'},inplace =True)

In [ ]:
#remover linha
df.drop(index=0,inplace=True)

In [ ]:
#grafico ano rim
sns.lineplot(x='Ano',y='Rim',data=df)
plt.show()

In [ ]:
#grafico total orgaos ano
sns.lineplot(x='Ano',y='Total Orgãos',data=df)
plt.show()

In [ ]:
#grafico ano com mais orgaos
sns.barplot(x='Ano',y='Total Orgãos',data=df)
plt.show()

In [ ]:
#grafico todos os orgaos
sns.lineplot(x='Ano',y='Total Geral',data=df)
plt.show()

In [ ]:
#salvar dataset
df.to_csv('Relatório de Transplantes Realizados (Rio Grande do Norte) - Evolução 2001 - 2023 - Table 1.csv',index=False)

In [ ]:
df.head(22)

,Ano,Coração,Fígado,Figado vivo,Figado falecido,Pancreas,Pulmão,Pulmão vivo,Pulmão falecido,Rim,...,Pancreas rim,Intestino Isolado,Multivisceral,Total Orgãos,Córnea,Médula óssea,MO Autólogo,Mo Aparentado,Mo Nap,Total Geral
1,2013,0,3,0,3,0,0,0,0,60,...,0,0,0,63,181,50,21,20,9,294
2,2014,2,2,0,2,0,0,0,0,66,...,0,0,0,70,141,60,31,17,12,271
3,2015,0,0,0,0,0,0,0,0,67,...,0,0,0,67,131,39,20,10,9,237
4,2016,0,0,0,0,0,0,0,0,67,...,0,0,0,67,104,57,24,17,16,228
5,2017,0,0,0,0,0,0,0,0,60,...,0,0,0,60,177,1,1,0,0,238
6,2018,0,0,0,0,0,0,0,0,45,...,0,0,0,45,166,59,42,9,8,270
7,2019,0,0,0,0,0,0,0,0,76,...,0,0,0,76,140,71,49,14,8,287
8,2020,0,0,0,0,0,0,0,0,48,...,0,0,0,48,92,91,63,21,7,231
9,2021,0,0,0,0,0,0,0,0,18,...,0,0,0,18,97,71,40,23,8,186
10,2022,2,0,0,0,0,0,0,0,48,...,0,0,0,50,135,52,27,15,10,237
11,2023,4,0,0,0,0,0,0,0,53,...,0,0,0,57,159,87,62,18,7,303

In [ ]:
from google.colab import files
files.download('Relatório de Transplantes Realizados (Rio Grande do Norte) - Evolução 2001 - 2023 - Table 1.csv')

In [5]:
df=pd.read_csv('/content/Relatório de Transplantes Realizados (Rio Grande do Norte) - Evolução 2001 - 2023 - Table 1 (1).csv')
df.head(22)

,Ano,Coração,Fígado,Figado vivo,Figado falecido,Pancreas,Pulmão,Pulmão vivo,Pulmão falecido,Rim,...,Pancreas rim,Intestino Isolado,Multivisceral,Total Orgãos,Córnea,Médula óssea,MO Autólogo,Mo Aparentado,Mo Nap,Total Geral
0,2013,0,3,0,3,0,0,0,0,60,...,0,0,0,63,181,50,21,20,9,294
1,2014,2,2,0,2,0,0,0,0,66,...,0,0,0,70,141,60,31,17,12,271
2,2015,0,0,0,0,0,0,0,0,67,...,0,0,0,67,131,39,20,10,9,237
3,2016,0,0,0,0,0,0,0,0,67,...,0,0,0,67,104,57,24,17,16,228
4,2017,0,0,0,0,0,0,0,0,60,...,0,0,0,60,177,1,1,0,0,238
5,2018,0,0,0,0,0,0,0,0,45,...,0,0,0,45,166,59,42,9,8,270
6,2019,0,0,0,0,0,0,0,0,76,...,0,0,0,76,140,71,49,14,8,287
7,2020,0,0,0,0,0,0,0,0,48,...,0,0,0,48,92,91,63,21,7,231
8,2021,0,0,0,0,0,0,0,0,18,...,0,0,0,18,97,71,40,23,8,186
9,2022,2,0,0,0,0,0,0,0,48,...,0,0,0,50,135,52,27,15,10,237
10,2023,4,0,0,0,0,0,0,0,53,...,0,0,0,57,159,87,62,18,7,303

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Ano                11 non-null     int64
 1   Coração            11 non-null     int64
 2   Fígado             11 non-null     int64
 3   Figado vivo        11 non-null     int64
 4   Figado falecido    11 non-null     int64
 5   Pancreas           11 non-null     int64
 6   Pulmão             11 non-null     int64
 7   Pulmão vivo        11 non-null     int64
 8   Pulmão falecido    11 non-null     int64
 9   Rim                11 non-null     int64
 10  Rim vivo           11 non-null     int64
 11  Rim falecido       11 non-null     int64
 12  Pancreas rim       11 non-null     int64
 13  Intestino Isolado  11 non-null     int64
 14  Multivisceral      11 non-null     int64
 15  Total Orgãos       11 non-null     int64
 16  Córnea             11 non-null     int64
 17  Médula óssea       11 non-null     int64
 18  MO Autólogo        11 non-null     int64
 19  Mo Aparentado      11 non-null     int64
 20  Mo Nap             11 non-null     int64
 21  Total Geral        11 non-null     int64
dtypes: int64(22)
memory usage: 2.0 KB

In [7]:
df.describe()

,Ano,Coração,Fígado,Figado vivo,Figado falecido,Pancreas,Pulmão,Pulmão vivo,Pulmão falecido,Rim,...,Pancreas rim,Intestino Isolado,Multivisceral,Total Orgãos,Córnea,Médula óssea,MO Autólogo,Mo Aparentado,Mo Nap,Total Geral
count,11.000000,11.000000,11.000000,11.0,11.000000,11.0,11.0,11.0,11.0,11.000000,...,11.0,11.0,11.0,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,2018.000000,0.727273,0.454545,0.0,0.454545,0.0,0.0,0.0,0.0,55.272727,...,0.0,0.0,0.0,56.454545,138.454545,58.000000,34.545455,14.909091,8.545455,252.909091
std,3.316625,1.348400,1.035725,0.0,1.035725,0.0,0.0,0.0,0.0,15.716812,...,0.0,0.0,0.0,16.021009,31.010849,24.462216,18.864589,6.549115,3.856518,35.049835
min,2013.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,18.000000,...,0.0,0.0,0.0,18.000000,92.000000,1.000000,1.000000,0.000000,0.000000,186.000000
25%,2015.500000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,48.000000,...,0.0,0.0,0.0,49.000000,117.500000,51.000000,22.500000,12.000000,7.500000,234.000000
50%,2018.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,60.000000,...,0.0,0.0,0.0,60.000000,140.000000,59.000000,31.000000,17.000000,8.000000,238.000000
75%,2020.500000,1.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,66.500000,...,0.0,0.0,0.0,67.000000,162.500000,71.000000,45.500000,19.000000,9.500000,279.000000
max,2023.000000,4.000000,3.000000,0.0,3.000000,0.0,0.0,0.0,0.0,76.000000,...,0.0,0.0,0.0,76.000000,181.000000,91.000000,63.000000,23.000000,16.000000,303.000000